FROM tnh-base-arm

RUN git clone -b test https://github.com/calvindo95/tnh-http-server.git && \
    cd tnh-http-server/include && wget https://github.com/nlohmann/json/releases/download/v3.11.2/json.hpp && cd .. && \
    mkdir build && cd build && \
    cmake .. && \
    cmake --build . -j4

WORKDIR /home/webserver/tnh-http-server

CMD ["/home/webserver/tnh-http-server/scripts/run_server.sh"]